# Plagentic Configuration Template
# Agentic AI Infrastructure Provisioning Platform

# Note: Team configurations are now managed in the /teams directory
# Copy this file to config.yaml and configure your API keys


# Model Configuration
models:
  openai:
    api_base: "https://api.openai.com/v1"
    api_key: "${OPENAI_API_KEY}"
    models: [ "gpt-4o", "gpt-4o-mini", "gpt-4-turbo" ]

  claude:
    api_base: "https://api.anthropic.com/v1"
    api_key: "${ANTHROPIC_API_KEY}"
    models: [ "claude-3-5-sonnet-20241022", "claude-3-5-haiku-20241022", "claude-3-opus-20240229" ]

  deepseek:
    api_base: "https://api.deepseek.com/v1"
    api_key: "${DEEPSEEK_API_KEY}"
    models: [ "deepseek-chat", "deepseek-coder" ]

# Tool Configuration
tools:
  searchGoogle:
    # Get your API key from https://serper.dev/
    api_key: "${SERPER_API_KEY}"
  
  terminal:
    enabled: true
    timeout: 30
  
  saveFile:
    enabled: true
    base_path: "./workspace"

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "plagentic.log"

# Security Configuration (Not implemented yet)
security:
  rbac_enabled: false
  keycloak_url: "${KEYCLOAK_URL}"
  realm: "plagentic"